export enum LoginActionTypes {
  CHANGE_LOGIN_EMAIL = "CHANGE_LOGIN_EMAIL",
  CHANGE_LOGIN_PASSWORD = "CHANGE_LOGIN_PASSWORD",
  LOGIN_IS_FETCHING = "LOGIN_IS_FETCHING",
  LOGOUT_IS_FETCHING = "LOGOUT_IS_FETCHING",
  LOGOUT_REDIRECT_LOGIN = "LOGOUT_REDIRECT_LOGIN",
}
